spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lightdigital
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/main-changelog.xml