spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lightdigital
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always