DROP TABLE IF EXISTS users, requests CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR,
    phone VARCHAR,
    password VARCHAR,
    role VARCHAR,
    CONSTRAINT pk_user
                PRIMARY KEY (id),
            CONSTRAINT UQ_USER_PHONE
                UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_request VARCHAR,
    description VARCHAR,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_requests_to_user
                FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);